language: go

os:
        - linux
        - osx
go:
        - 1.3
        - 1.4
        - 1.5
        - tip

before_install:
        - go get github.com/axw/gocov/gocov
        - go get github.com/mattn/goveralls
        - go get golang.org/x/tools/cmd/cover

install:
        - go get github.com/golang/lint/golint

env:
        - GIMME_OS=linux GIMME_ARCH=amd64

script:
        - $HOME/gopath/bin/goveralls -repotoken NI9fnGqoyN7iSNCLiAtwphZGIuw54bX5E
        - test -z "$(go fmt ./...)"
        - test -z "$(go vet ./...)"
        - test -z "$(golint)"
        - go test .
